# -*- coding: utf-8 -*-

MODULO = 'hemored_hemovigilancia'
BORRADOR = 'borrador'
ENVIADO = 'enviado'
VALIDADO = 'validado'

SELECTION_INSTITUCION = [
    ('1', 'MINSA'),
    ('2', 'ESSALUD'),
    ('3', 'SANIDAD DEL EJERCITO DEL PERU'),
    ('4', 'SANIDAD DE LA FUERZA AEREA DEL PERU'),
    ('5', 'SANIDAD DE LA POLICIA NACIONAL DEL PERU'),
    ('6', 'SANIDAD DE LA MARINA DE GUERRA DEL PERU'),
    ('7', 'GOBIERNO REGIONAL'),
    ('8', 'MUNICIPALIDAD PROVINCIAL'),
    ('9', 'MUNICIPALIDAD DISTRITAL'),
    ('10', 'PRIVADO'),
    ('13', 'INPE'),
    ('11', 'OTRO'),
]

SELECTION_ESTADO_FICHA = [
    (BORRADOR, 'Borrador'),
    (ENVIADO, 'Enviado'),
    (VALIDADO, 'Validado'),
]

SELECTION_INSTITUCION_1 = 'MINSA'
SELECTION_INSTITUCION_2 = 'ESSALUD'
SELECTION_INSTITUCION_3 = 'SANIDAD DEL EJERCITO DEL PERU'
SELECTION_INSTITUCION_4 = 'SANIDAD DE LA FUERZA AEREA DEL PERU'
SELECTION_INSTITUCION_5 = 'SANIDAD DE LA POLICIA NACIONAL DEL PERU'
SELECTION_INSTITUCION_6 = 'SANIDAD DE LA MARINA DE GUERRA DEL PERU'
SELECTION_INSTITUCION_7 = 'GOBIERNO REGIONAL'
SELECTION_INSTITUCION_8 = 'MUNICIPALIDAD PROVINCIAL'
SELECTION_INSTITUCION_9 = 'MUNICIPALIDAD DISTRITAL'
SELECTION_INSTITUCION_10 = 'PRIVADO'
SELECTION_INSTITUCION_13 = 'INPE'
SELECTION_INSTITUCION_11 = 'OTRO'

TIPO_BANCO_1 = 'tipo I'
TIPO_BANCO_2 = 'tipo II'

MAP_FIELD_CELDA = {
    # Tamizaje unidades
    'cantidad_mvih_clt_cv': 'I',
    'cantidad_mvih_clt_cr': 'J',
    'cantidad_mvih_clt_cpr': 'K',
    'cantidad_mvih_clt_ca': 'L',
    'cantidad_mvih_clt_total': 'M',
    'cantidad_mvih_clr_cv': 'N',
    'cantidad_mvih_clr_cr': 'O',
    'cantidad_mvih_clr_cpr': 'P',
    'cantidad_mvih_clr_ca': 'Q',
    'cantidad_mvih_clr_total': 'R',
    'cantidad_mvih_clzg_cv': 'S',
    'cantidad_mvih_clzg_cr': 'T',
    'cantidad_mvih_clzg_cpr': 'U',
    'cantidad_mvih_clzg_ca': 'V',
    'cantidad_mvih_clzg_total': 'W',
    'cantidad_mhbsag_clt_cv': 'X',
    'cantidad_mhbsag_clt_cr': 'Y',
    'cantidad_mhbsag_clt_cpr': 'Z',
    'cantidad_mhbsag_clt_ca': 'AA',
    'cantidad_mhbsag_clt_total': 'AB',
    'cantidad_mhbsag_clr_cv': 'AC',
    'cantidad_mhbsag_clr_cr': 'AD',
    'cantidad_mhbsag_clr_cpr': 'AE',
    'cantidad_mhbsag_clr_ca': 'AF',
    'cantidad_mhbsag_clr_total': 'AG',
    'cantidad_mhbsag_clzg_cv': 'AH',
    'cantidad_mhbsag_clzg_cr': 'AI',
    'cantidad_mhbsag_clzg_cpr': 'AJ',
    'cantidad_mhbsag_clzg_ca': 'AK',
    'cantidad_mhbsag_clzg_total': 'AL',
    'cantidad_mhepc_clt_cv': 'AM',
    'cantidad_mhepc_clt_cr': 'AN',
    'cantidad_mhepc_clt_cpr': 'AO',
    'cantidad_mhepc_clt_ca': 'AP',
    'cantidad_mhepc_clt_total': 'AQ',
    'cantidad_mhepc_clr_cv': 'AR',
    'cantidad_mhepc_clr_cr': 'AS',
    'cantidad_mhepc_clr_cpr': 'AT',
    'cantidad_mhepc_clr_ca': 'AU',
    'cantidad_mhepc_clr_total': 'AV',
    'cantidad_mhepc_clzg_cv': 'AW',
    'cantidad_mhepc_clzg_cr': 'AX',
    'cantidad_mhepc_clzg_cpr': 'AY',
    'cantidad_mhepc_clzg_ca': 'AZ',
    'cantidad_mhepc_clzg_total': 'BA',
    'cantidad_mantihbc_clt_cv': 'BB',
    'cantidad_mantihbc_clt_cr': 'BC',
    'cantidad_mantihbc_clt_cpr': 'BD',
    'cantidad_mantihbc_clt_ca': 'BE',
    'cantidad_mantihbc_clt_total': 'BF',
    'cantidad_mantihbc_clr_cv': 'BG',
    'cantidad_mantihbc_clr_cr': 'BH',
    'cantidad_mantihbc_clr_cpr': 'BI',
    'cantidad_mantihbc_clr_ca': 'BJ',
    'cantidad_mantihbc_clr_total': 'BK',
    'cantidad_mantihbc_clzg_cv': 'BL',
    'cantidad_mantihbc_clzg_cr': 'BM',
    'cantidad_mantihbc_clzg_cpr': 'BN',
    'cantidad_mantihbc_clzg_ca': 'BO',
    'cantidad_mantihbc_clzg_total': 'BP',
    'cantidad_mhtlv_clt_cv': 'BQ',
    'cantidad_mhtlv_clt_cr': 'BR',
    'cantidad_mhtlv_clt_cpr': 'BS',
    'cantidad_mhtlv_clt_ca': 'BT',
    'cantidad_mhtlv_clt_total': 'BU',
    'cantidad_mhtlv_clr_cv': 'BV',
    'cantidad_mhtlv_clr_cr': 'BW',
    'cantidad_mhtlv_clr_cpr': 'BX',
    'cantidad_mhtlv_clr_ca': 'BY',
    'cantidad_mhtlv_clr_total': 'BZ',
    'cantidad_mhtlv_clzg_cv': 'CA',
    'cantidad_mhtlv_clzg_cr': 'CB',
    'cantidad_mhtlv_clzg_cpr': 'CC',
    'cantidad_mhtlv_clzg_ca': 'CD',
    'cantidad_mhtlv_clzg_total': 'CE',
    'cantidad_msifilis_clt_cv': 'CF',
    'cantidad_msifilis_clt_cr': 'CG',
    'cantidad_msifilis_clt_cpr': 'CH',
    'cantidad_msifilis_clt_ca': 'CI',
    'cantidad_msifilis_clt_total': 'CJ',
    'cantidad_msifilis_clr_cv': 'CK',
    'cantidad_msifilis_clr_cr': 'CL',
    'cantidad_msifilis_clr_cpr': 'CM',
    'cantidad_msifilis_clr_ca': 'CN',
    'cantidad_msifilis_clr_total': 'CO',
    'cantidad_msifilis_clzg_cv': 'CP',
    'cantidad_msifilis_clzg_cr': 'CQ',
    'cantidad_msifilis_clzg_cpr': 'CR',
    'cantidad_msifilis_clzg_ca': 'CS',
    'cantidad_msifilis_clzg_total': 'CT',
    'cantidad_mchagas_clt_cv': 'CU',
    'cantidad_mchagas_clt_cr': 'CV',
    'cantidad_mchagas_clt_cpr': 'CW',
    'cantidad_mchagas_clt_ca': 'CX',
    'cantidad_mchagas_clt_total': 'CY',
    'cantidad_mchagas_clr_cv': 'CZ',
    'cantidad_mchagas_clr_cr': 'DA',
    'cantidad_mchagas_clr_cpr': 'DB',
    'cantidad_mchagas_clr_ca': 'DC',
    'cantidad_mchagas_clr_total': 'DD',
    'cantidad_mchagas_clzg_cv': 'DE',
    'cantidad_mchagas_clzg_cr': 'DF',
    'cantidad_mchagas_clzg_cpr': 'DG',
    'cantidad_mchagas_clzg_ca': 'DH',
    'cantidad_mchagas_clzg_total': 'DI',
    'cantidad_motros_clt_cv': 'DJ',
    'cantidad_motros_clt_cr': 'DK',
    'cantidad_motros_clt_cpr': 'DL',
    'cantidad_motros_clt_ca': 'DM',
    'cantidad_motros_clt_total': 'DN',
    'cantidad_motros_clr_cv': 'DO',
    'cantidad_motros_clr_cr': 'DP',
    'cantidad_motros_clr_cpr': 'DQ',
    'cantidad_motros_clr_ca': 'DR',
    'cantidad_motros_clr_total': 'DS',
    'cantidad_motros_clzg_cv': 'DT',
    'cantidad_motros_clzg_cr': 'DU',
    'cantidad_motros_clzg_cpr': 'DV',
    'cantidad_motros_clzg_ca': 'DW',
    'cantidad_motros_clzg_total': 'DX',
    # DEMANDA DE HEMOCOMPONENTE
    'cantidad_ds_hgr': 'I',
    'cantidad_da_hgr': 'J',
    # ELIMINACIÓN DE SANGRE Y HEMOCOMPONENTES
    'cantidad_cv_hgr': 'I',
    'cantidad_cmitt_hgr': 'J',
    'cantidad_ca_hgr': 'K',
    'cantidad_ct_hgr': 'L',
    'cantidad_cp_hgr': 'M',
    'cantidad_co_hgr': 'N',
}
MAP_FIELD_CELDA_2 = {
    # Tamizaje unidades
    'cantidad_mvih_clt_total': 'D',
    'cantidad_mvih_clr_total': 'E',
    'cantidad_mvih_clzg_total': 'F',
    'cantidad_mhbsag_clt_total': 'G',
    'cantidad_mhbsag_clr_total': 'H',
    'cantidad_mhbsag_clzg_total': 'I',
    'cantidad_mhepc_clt_total': 'J',
    'cantidad_mhepc_clr_total': 'K',
    'cantidad_mhepc_clzg_total': 'L',
    'cantidad_mantihbc_clt_total': 'M',
    'cantidad_mantihbc_clr_total': 'N',
    'cantidad_mantihbc_clzg_total': 'O',
    'cantidad_mhtlv_clt_total': 'P',
    'cantidad_mhtlv_clr_total': 'Q',
    'cantidad_mhtlv_clzg_total': 'R',
    'cantidad_msifilis_clt_total': 'S',
    'cantidad_msifilis_clr_total': 'T',
    'cantidad_msifilis_clzg_total': 'U',
    'cantidad_mchagas_clt_total': 'V',
    'cantidad_mchagas_clr_total': 'W',
    'cantidad_mchagas_clzg_total': 'X',
    'cantidad_motros_clt_total': 'Y',
    'cantidad_motros_clr_total': 'Z',
    'cantidad_motros_clzg_total': 'AA',
}
